### PR TITLE
Add support for typed array properties

### PR DESCRIPTION
**Pull request by artemave**
E.g.

```js
class Post extends ValueObject.define({
  tags: ['string'],
  comments: [Comment] // array of Comment instances
}) {}

### CODE REVIEW

**Comment by joshski** [comment]
Thanks @artemave, I really like the idea and the implementation! Generically typed JavaScript collections, who'd have thought? 😲 

But I'm not sure about the change to the readme. In my mind, posts and comments are not a good example of something that remains the same "value" over time. It's a subtle point but "Great British Pound" and "the tenner in my pocket" mean the same thing from day to day, whereas it's not unusual for comments and posts to be updated, so they are more traditionally modelled as [entities](http://culttt.com/2014/04/30/difference-entities-value-objects/). Money and currency are also super typical examples of value objects (probably in the Domain Driven Design book, I haven't read it in a while!) hence why I chose those.

However the value of money in relation to _other_ things varies, so perhaps that's where we can introduce typed arrays into the example. Perhaps a better example of an array of value objects would be foreign exchange index: a list of ExchangeRate instances over time.

**Comment by artemave** [comment]
@joshski agreed. The original example was better and simpler. I couldn't come up with a meaningful example to build upon Money/Currency. Hence the change to Post/Comment.

I'll revert it back and add a section about typed arrays.

**Comment by artemave** [comment]
@joshski check out the readme - it looks better now

**Comment by joshski** [comment]
Great stuff, thanks @artemave!

**Pull request merged**
