### PR TITLE
ES5 Rewrite

### PR DESCRIPTION
**Pull request by joshski**
A rewrite from scratch with the following goals in mind:

* Allow nested type definitions e.g.
```js
ValueObject.define({ currency: { code: 'string' }, amount: 'number' })
```
* More modular schema definition code, which e.g. allows custom property types:
```js
ValueObject.definePropertyType('money', {
  coerce(value) {
    const parts = value.split(' ')
    return { amount: Number(parts[0]), currency: parts[1] }
  },

  areEqual(a, b) {
    return a.currency == b.currency && a.amount == b.amount
  }
})
const Allowance = ValueObject.define({ cash: 'money' })
```
* Don't validate argument types _and then_ convert arguments to value objects, do both in one go, for performance and to simplify the code.

* Avoid babel issues [like this one](https://github.com/cucumber-ltd/value-object.js/issues/2)

* Improve error messages

Supersedes https://github.com/cucumber-ltd/value-object.js/pull/4

There are some minor breaking changes, namely `Scalar` now has functions instead of getter properties for `uriEncoded`, `uriComponentEncoded` and `queryEncoded`.

### CODE REVIEW

**Comment by artemave** [comment]
Confusing error when using `define` via es6 destructing assignment: `const {define} = require('value-object')`

```
Error: ValueObject.define() cannot be called on subclasses
```

`const ValueObject = require('value-object')` works as expected

**Comment by artemave** [comment]
`TypeError` is now `Error` which is a bit generic to catch

image

Ideally it should be even more specific than `TypeError` but that's probably outside of the scope of this pr.

**Comment by mattwynne** [comment]
@joshski is this "done"?

**Comment by joshski** [comment]
Well... in my opinion it’s better than what’s in master in a number of ways. Mainly that it’s simpler, more extensible, and generates more useful errors. It should be a relatively easy upgrade for any users.

We’ve just discovered one little hiccup related to a bug in babel, when subclassing a value object and transpiling for IE10 or lower.

If that’s not an issue for you, it would be great

**Comment by joshski** [comment]
21 commits later and it seems I now have all tests passing in all projects that I am aware of depending on this library. So I am merging this change and releasing 0.1.0

Releasing is highest priority, but I will bump up to 1.0.0 when I have had a chance to improve the documentation and formatting of the code.

**Pull request merged**
